import pandas as pd

# Para el procesado de los dataasets deberán ser descargados a través de los enlaces incluídos en el README.md
# Posteriormente hay que introducirlos en la carpeta 'original'  

cost_living=pd.read_csv('datasets/original/cost_of_living.csv')
gpd=pd.read_csv('datasets/original/countries_gdp_hist.csv', delimiter=';')
richest=pd.read_csv('datasets/original/richest500.csv', delimiter=';')
country_mapper_cost_living= {
    'Bermuda': 'BERMUDA',
    'Switzerland': 'SWITZERLAND',
    'Cayman Islands': 'CAYMAN ISLANDS',
    'Israel': 'ISRAEL',
    'Iceland': 'ICELAND',
    'New Caledonia': 'NEW CALEDONIA',
    'Turks and Caicos Islands': 'TURKS AND CAICOS ISLANDS',
    'Norway': 'NORWAY',
    'Barbados': 'BARBADOS',
    'Denmark': 'DENMARK',
    'Ireland': 'IRELAND',
    'Australia': 'AUSTRALIA',
    'New Zealand': 'NEW ZEALAND',
    'Luxembourg': 'LUXEMBOURG',
    'Sweden': 'SWEDEN',
    'Finland': 'FINLAND',
    'United Kingdom': 'UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND',
    'Canada': 'CANADA',
    'Japan': 'JAPAN',
    'United States': 'UNITED STATES OF AMERICA',
    'Netherlands': 'NETHERLANDS',
    'Belgium': 'BELGIUM',
    'France': 'FRANCE',
    'Austria': 'AUSTRIA',
    'Germany': 'GERMANY',
    'South Korea': 'KOREA, REPUBLIC OF',
    'Italy': 'ITALY',
    'Spain': 'SPAIN',
    'Hong Kong': 'HONG KONG',
    'Portugal': 'PORTUGAL',
    'Malta': 'MALTA',
    'Singapore': 'SINGAPORE',
    'Macao': 'MACAO',
    'Greece': 'GREECE',
    'Estonia': 'ESTONIA',
    'United Arab Emirates': 'UNITED ARAB EMIRATES',
    'Qatar': 'QATAR',
    'Czechia': 'CZECHIA',
    'Iran': 'IRAN (ISLAMIC REPUBLIC OF)',
    'China': 'CHINA',
    'Chile': 'CHILE',
    'Croatia': 'CROATIA',
    'Haiti': 'HAITI',
    'Costa Rica': 'COSTA RICA',
    'Hungary': 'HUNGARY',
    'Equatorial Guinea': 'EQUATORIAL GUINEA',
    'Mexico': 'MEXICO',
    'Albania': 'ALBANIA',
    'Ecuador': 'ECUADOR',
    'Serbia': 'SERBIA',
    'Montenegro': 'MONTENEGRO',
    'Poland': 'POLAND',
    'Bahrain': 'BAHRAIN',
    'Brunei': 'BRUNEI DARUSSALAM',
    'Bulgaria': 'BULGARIA',
    'Romania': 'ROMANIA',
    'South Africa': 'SOUTH AFRICA',
    'Brazil': 'BRAZIL',
    'Morocco': 'MOROCCO',
    'Saudi Arabia': 'SAUDI ARABIA',
    'Mauritius': 'MAURITIUS',
    'Ivory Coast': "CÔTE D'IVOIRE",
    'Kenya': 'KENYA',
    'Cameroon': 'CAMEROON',
    'Timor-Leste': 'TIMOR-LESTE',
    'Colombia': 'COLOMBIA',
    'Nigeria': 'NIGERIA',
    'Kosovo': 'KOSOVO',
    'Philippines': 'PHILIPPINES',
    'Lesotho': 'LESOTHO',
    'Bangladesh': 'BANGLADESH',
    'Malaysia': 'MALAYSIA',
    'Paraguay': 'PARAGUAY',
    'Moldova': 'MOLDOVA, REPUBLIC OF',
    'Thailand': 'THAILAND',
    'Benin': 'BENIN',
    'Ghana': 'GHANA',
    'Russia': 'RUSSIAN FEDERATION',
    'Iraq': 'IRAQ',
    'Cambodia': 'CAMBODIA',
    'Bolivia': 'BOLIVIA (PLURINATIONAL STATE OF)',
    'Nicaragua': 'NICARAGUA',
    'Indonesia': 'INDONESIA',
    'Mongolia': 'MONGOLIA',
    'Suriname': 'SURINAME',
    'Vietnam': 'VIET NAM',
    'Turkey': 'TURKEY',
    'Tanzania': 'TANZANIA, UNITED REPUBLIC OF',
    'Armenia': 'ARMENIA',
    'Laos': "LAO PEOPLE'S DEMOCRATIC REPUBLIC",
    'Kazakhstan': 'KAZAKHSTAN',
    'Georgia': 'GEORGIA',
    'Zambia': 'ZAMBIA',
    'Tunisia': 'TUNISIA',
    'Sri Lanka': 'SRI LANKA',
    'Bhutan': 'BHUTAN',
    'Ukraine': 'UKRAINE',
    'Algeria': 'ALGERIA',
    'Azerbaijan': 'AZERBAIJAN',
    'India': 'INDIA',
    'Nepal': 'NEPAL',
    'Egypt': 'EGYPT',
    'Burma': 'MYANMAR',
    'Pakistan': 'PAKISTAN',
    'Kyrgyzstan': 'KYRGYZSTAN',
    'Angola': 'ANGOLA',
    'Tajikistan': 'TAJIKISTAN'
}

country_mapper_richest = {
    'United States': 'UNITED STATES OF AMERICA',
    'France': 'FRANCE',
    'Spain': 'SPAIN',
    'India': 'INDIA',
    'China': 'CHINA',
    'Mexico': 'MEXICO',
    'Japan': 'JAPAN',
    'Italy': 'ITALY',
    'Germany': 'GERMANY',
    'Russia': 'RUSSIAN FEDERATION',
    'Hong Kong': 'HONG KONG',
    'Australia': 'AUSTRALIA',
    'United Kingdom': 'UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND',
    'Ireland': 'IRELAND',
    'Chile': 'CHILE',
    'Brazil': 'BRAZIL',
    'Sweden': 'SWEDEN',
    'Singapore': 'SINGAPORE',
    'Malaysia': 'MALAYSIA',
    'Switzerland': 'SWITZERLAND',
    'Austria': 'AUSTRIA',
    'Netherlands': 'NETHERLANDS',
    'Saudi Arabia': 'SAUDI ARABIA',
    'Nigeria': 'NIGERIA',
    'Indonesia': 'INDONESIA',
    'Thailand': 'THAILAND',
    'Canada': 'CANADA',
    'Colombia': 'COLOMBIA',
    'Korea': 'KOREA, REPUBLIC OF',
    'South Korea': 'KOREA, REPUBLIC OF',
    'Israel': 'ISRAEL',
    'Monaco': 'MONACO',
    'Denmark': 'DENMARK',
    'New Zealand': 'NEW ZEALAND',
    'Viet Nam': 'VIET NAM',
    'Vietnam': 'VIET NAM',
    'Ukraine': 'UKRAINE',
    'Cyprus': 'CYPRUS',
    'South Africa': 'SOUTH AFRICA',
    'Canda': 'CANADA',
    'Romania': 'ROMANIA',
    'Taiwan': 'TAIWAN',
    'Finland': 'FINLAND',
    'Egypt': 'EGYPT',
    'Cayman Islands': 'CAYMAN ISLANDS',
    'Norway': 'NORWAY',
    'Philippines': 'PHILIPPINES',
    'United Arab Emirates': 'UNITED ARAB EMIRATES',
    'Argentina': 'ARGENTINA',
    'Georgia': 'GEORGIA',
    'Kazakhstan': 'KAZAKHSTAN'
}

import pandas as pd

def standardize_country_names(df, column_name, mapping):
    df[column_name] = df[column_name].map(mapping).fillna(df[column_name])
    return df

df_cost_living = standardize_country_names(cost_living, 'country', country_mapper_cost_living)
df_cost_living.to_csv('datasets/processed/cost_living_processed.csv', index=False)

df_richest = standardize_country_names(richest, 'Country', country_mapper_richest)
df_richest.to_csv('datasets/processed/richest_processed.csv', index=False)

gpd_2021=gpd[gpd.year==2021]
gpd_2021.drop(columns=['year'], inplace=True)
gpd_2021=gpd_2021.reset_index(drop=True)
gpd_2021.to_csv('datasets/processed/gpd_2021_processed.csv', index=False)